name: "Build"
on:
  workflow_dispatch:
  push:
jobs:
  build:
    strategy:
      matrix:
        package: [nushell, nushellFull]
        os: [ubuntu-latest, macos-latest]
        arch:
          - x86_64
          # - aarch64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: nushell-nightly
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build .#${{ matrix.package }}
