name: "Build"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "_sources"
jobs:
  build-x86_64:
    strategy:
      matrix:
        package: [nushell, nushellFull]
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: nushell-nightly
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build .#${{ matrix.package }}
  build-aarch64:
    strategy:
      matrix:
        package: [nushell, nushellFull]
        os:
          - ubuntu-latest
          # - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - run: sudo apt-get install -y qemu-user-static
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            system = aarch64-linux
      - uses: cachix/cachix-action@v12
        with:
          name: nushell-nightly
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build
        run: nix build .#${{ matrix.package }}
