name: "Build"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "npins/**"
      - "flake.*"
      - "nushell.nix"
jobs:
  build:
    strategy:
      matrix:
        package:
          [
            nushell,
            nushellFull,
            nu_plugin_formats,
            nu_plugin_gstat,
            nu_plugin_inc,
            nu_plugin_query,
            nu_plugin_polars,
          ]
        os: [linux, darwin]
        arch: [aarch64, x86_64]
        exclude:
          - os: darwin
            arch: aarch64
      fail-fast: false
    runs-on: ${{ matrix.os == 'linux' && 'ubuntu-latest' || 'macos-latest' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup QEMU
        if: matrix.os == 'linux' && matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      # - run: sudo apt-get install -y qemu-user-static
      - uses: cachix/install-nix-action@v25
        # with:
        #   extra_nix_config: |
        #     system = ${{ matrix.arch }}-${{ matrix.os }}
      - uses: cachix/cachix-action@v14
        with:
          name: nushell-nightly
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: DeterminateSystems/magic-nix-cache-action@v3
      - run: nix build .#${{ matrix.package }} --option system ${{ matrix.arch }}-${{ matrix.os }}
