name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: joaquin
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build .#nushell
      - run: nix build .#nushellFull
      - run: nix-shell --run "echo OK"
