name: "Update flake"
on:
  workflow_dispatch:
  schedule:
    # daily at 00:00
    - cron: "0 0 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.COMMIT_KEY }}
      - uses: cachix/install-nix-action@v25
      - run: |
          git config user.name 'flake updater'
          git config user.email 'noreply@github.com'
          nix flake update --commit-lock-file
          git push
