name: "Update nushell"
on:
  workflow_dispatch:
  schedule:
    # every hour
    - cron: "0 * * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.PAT }}
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: |
          git config user.name 'nvfetcher updater'
          git config user.email 'noreply@github.com'
          nix run nixpkgs#nvfetcher -- --commit-changes
          git push
